on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: api.caddy.com.ar
        username: dinter6
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /api.caddy.com.ar/
        timeout: 60000
